modLoader = "javafml" #mandatory
loaderVersion = "[36,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.
license = "GNU Lesser General Public License"
[[mods]] #mandatory
modId = "aeinfinitybooster" #mandatory
version = "${file.jarVersion}" #mandatory
displayName = "AEInfinityBooster" #mandatory
description = '''

'''
[[dependencies.aeinfinitybooster]] #optional
modId = "forge" #mandatory
mandatory = true #mandatory
versionRange = "[36,)" #mandatory
ordering = "NONE"
side = "BOTH"
[[dependencies.aeinfinitybooster]]
modId = "minecraft"
mandatory = true
versionRange = "[1.16.5,1.17)"
ordering = "NONE"
side = "BOTH"
[[dependencies.aeinfinitybooster]]
modId = "appliedenergistics2"
versionRange = "[8.4.4,)"
mandatory = true
ordering = "AFTER"
side = "BOTH"